[project]

name = "src"
version = "0.0.1"
description = "An MLOps project for productionize Models"
authors = [{name = "Amit Kushwaha", email ="amitkushwaha43714@gmail.com" }]

[tool.setuptools]
packages = {find = {}}

[tool.setup.dynamic]
dependencies = {file = "requirements.txt"}