name: Deploy Application Docker Image to Azure VM

on:
  push:
    branches:
      - main

jobs:
  Continuous-Integration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: mlopsregistry4321.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and Push Docker Image to ACR
        env:
          ACR_REGISTRY: mlopsregistry4321.azurecr.io
          IMAGE_NAME: vehicle-insurance
          IMAGE_TAG: latest
        run: |
          docker build -t $ACR_REGISTRY/$IMAGE_NAME:$IMAGE_TAG .
          docker push $ACR_REGISTRY/$IMAGE_NAME:$IMAGE_TAG

  Continuous-Deployment:
    needs: Continuous-Integration
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: mlopsregistry4321.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Pull and Run Docker Container on Azure VM
        env:
          ACR_REGISTRY: mlopsregistry4321.azurecr.io
          IMAGE_NAME: vehicle-insurance
          IMAGE_TAG: latest
        run: |
          docker pull $ACR_REGISTRY/$IMAGE_NAME:$IMAGE_TAG
          docker stop vehicle-insurance || true
          docker rm vehicle-insurance || true
          docker run -d -p 8000:8000 --name vehicle-insurance $ACR_REGISTRY/$IMAGE_NAME:$IMAGE_TAG
